/**
 * Spendies Backend API
 * This RESTful API is for accessing the back-end functionality of Spendies,  such as registering and verifying accounts, and creating and retrieving wallets, transaction requests, and performing transaction fullfilments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: connect@spendies.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SettlementStatus } from './settlementStatus';

export class LinkedData {
    /**
    * ID of Account
    */
    'linkedAccount'?: string;
    /**
    * ID of Wallet
    */
    'linkedWallet'?: string;
    'linkedSettlement'?: SettlementStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "linkedAccount",
            "baseName": "linkedAccount",
            "type": "string"
        },
        {
            "name": "linkedWallet",
            "baseName": "linkedWallet",
            "type": "string"
        },
        {
            "name": "linkedSettlement",
            "baseName": "linkedSettlement",
            "type": "SettlementStatus"
        }    ];

    static getAttributeTypeMap() {
        return LinkedData.attributeTypeMap;
    }
}

