/**
 * Spendies Backend API
 * This RESTful API is for accessing the back-end functionality of Spendies,  such as registering and verifying accounts, and creating and retrieving wallets, payment requests, and performing payment fullfilments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: connect@spendies.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LinkedAccount } from './linkedAccount';

export class OriginatorRecipient {
    /**
    * Name of recipient
    */
    'name'?: string;
    /**
    * Wallet address of recipient
    */
    'address': string;
    'links'?: LinkedAccount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "LinkedAccount"
        }    ];

    static getAttributeTypeMap() {
        return OriginatorRecipient.attributeTypeMap;
    }
}

