/**
 * Spendies Backend API
 * This RESTful API is for accessing the back-end functionality of Spendies,  such as registering and verifying accounts, and creating and retrieving wallets, transaction requests, and performing transaction fullfilments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: connect@spendies.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class SettlementStatus {
    /**
    * ID of Settlement
    */
    'settlementId': string;
    /**
    * Status of settlement
    */
    'status': SettlementStatus.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "settlementId",
            "baseName": "settlementId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SettlementStatus.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return SettlementStatus.attributeTypeMap;
    }
}

export namespace SettlementStatus {
    export enum StatusEnum {
        Open = <any> 'open',
        Pending = <any> 'pending',
        Cancelled = <any> 'cancelled',
        Completed = <any> 'completed',
        Expired = <any> 'expired',
        Refunded = <any> 'refunded'
    }
}
