/**
 * Spendies Backend API
 * This RESTful API is for accessing the back-end functionality of Spendies,  such as registering and verifying accounts, and creating and retrieving wallets, transaction requests, and performing transaction fullfilments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: connect@spendies.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Settlement } from './settlement';
import { SettlementWithIdAllOf } from './settlementWithIdAllOf';

export class SettlementWithId {
    /**
    * ID of Settlement
    */
    'settlementId': string;
    /**
    * Method of settlement
    */
    'method': SettlementWithId.MethodEnum;
    /**
    * Initiated date of settlement
    */
    'dateInitiated': Date;
    /**
    * Status of settlement
    */
    'status': SettlementWithId.StatusEnum;
    /**
    * Settle transaction through issuer
    */
    'issuer': string;
    /**
    * Currency to settle in
    */
    'currency': string;
    /**
    * Amount to be settled
    */
    'amount': number;
    /**
    * ID of Transaction
    */
    'linkedTx'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "settlementId",
            "baseName": "settlementId",
            "type": "string"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "SettlementWithId.MethodEnum"
        },
        {
            "name": "dateInitiated",
            "baseName": "dateInitiated",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SettlementWithId.StatusEnum"
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "linkedTx",
            "baseName": "linkedTx",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SettlementWithId.attributeTypeMap;
    }
}

export namespace SettlementWithId {
    export enum MethodEnum {
        Ideal = <any> 'ideal',
        Crypto = <any> 'crypto'
    }
    export enum StatusEnum {
        Open = <any> 'open',
        Pending = <any> 'pending',
        Cancelled = <any> 'cancelled',
        Completed = <any> 'completed',
        Expired = <any> 'expired',
        Refunded = <any> 'refunded'
    }
}
