/**
 * Spendies Backend API
 * This RESTful API is for accessing the back-end functionality of Spendies,  such as registering and verifying accounts, and creating and retrieving wallets, transaction requests, and performing transaction fullfilments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: connect@spendies.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TokenPayload {
    /**
    * Name of service provider
    */
    'iss': string;
    /**
    * Subscription (account id)
    */
    'sub': string;
    /**
    * Unique id of device
    */
    'dev': string;
    /**
    * Expire after time
    */
    'exp'?: number;
    /**
    * Issued at time
    */
    'iat'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "iss",
            "baseName": "iss",
            "type": "string"
        },
        {
            "name": "sub",
            "baseName": "sub",
            "type": "string"
        },
        {
            "name": "dev",
            "baseName": "dev",
            "type": "string"
        },
        {
            "name": "exp",
            "baseName": "exp",
            "type": "number"
        },
        {
            "name": "iat",
            "baseName": "iat",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TokenPayload.attributeTypeMap;
    }
}

