/**
 * Spendies Backend API
 * This RESTful API is for accessing the back-end functionality of Spendies,  such as registering and verifying accounts, and creating and retrieving wallets, payment requests, and performing payment fullfilments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: connect@spendies.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Wallet } from './wallet';
import { WalletWithIdAllOf } from './walletWithIdAllOf';

export class WalletWithId {
    /**
    * ID of Wallet
    */
    'walletId': string;
    /**
    * Display name of wallet
    */
    'name': string;
    /**
    * Address of wallet
    */
    'address': string;
    /**
    * Currency of wallet
    */
    'currency': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "walletId",
            "baseName": "walletId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WalletWithId.attributeTypeMap;
    }
}

